services:
  - type: web
    name: attendance-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5003
      - key: FLASK_ENV
        value: production
      - key: STUDENT_SERVICE_URL
        value: https://student-service.onrender.com
      - key: LECTURE_SERVICE_URL
        value: https://lecture-service.onrender.com
      - key: CLASS_SERVICE_URL
        value: https://class-service.onrender.com 